In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install fireducks # Si no está instalada la libería instalar con este comando

Requirement already satisfied: fireducks in /usr/local/lib/python3.12/dist-packages (1.4.4)
Requirement already satisfied: firefw==1.4.4 in /usr/local/lib/python3.12/dist-packages (from fireducks) (1.4.4)
Requirement already satisfied: pandas<2.4.0,>=1.5.3 in /usr/local/lib/python3.12/dist-packages (from fireducks) (2.2.2)
Requirement already satisfied: pyarrow<21.1,>=21.0 in /usr/local/lib/python3.12/dist-packages (from fireducks) (21.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=1.5.3->fireducks) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=1.5.3->fireducks) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=1.5.3->fireducks) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=1.5.3->fireducks) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=1.5.3->fireducks) (1.17.0)

In [ ]:
import pandas as pd
import fireducks.pandas as pd # la ventaja de esta libreria es que viene a reemplazar a pandas
                              # si queremos comparar o tener ambas debemos asignarle otro nombre
import numpy as np
from google.colab import files
import random

# **ENTREGAS**

* 1era 12-06-2025
* 2da: 26-06-2025
* Examen 07-07-2025

# **TITULADOS**

In [ ]:
df1= pd.read_csv('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/TITULADO_2007-2024_web_19_05_2025_E.csv',
                 sep = ';', encoding = 'latin-1',
                  low_memory = False, on_bad_lines = 'skip')

In [ ]:
df1.shape

(218566, 42)

In [ ]:
df1.head().T

,0,1,2,3,4
AÑO,TIT_2024,TIT_2024,TIT_2024,TIT_2024,TIT_2024
TOTAL TITULACIONES,10,13,15,19,9
TITULACIONES MUJERES POR PROGRAMA,4.0,10.0,13.0,15.0,5.0
TITULACIONES HOMBRES POR PROGRAMA,6.0,3.0,2.0,4.0,4.0
TITULACIONES NB E INDEFINIDO POR PROGRAMA,NaN,NaN,NaN,NaN,NaN
CLASIFICACIÓN INSTITUCIÓN NIVEL 1,Universidades,Universidades,Universidades,Universidades,Universidades
CLASIFICACIÓN INSTITUCIÓN NIVEL 2,Universidades Privadas,Universidades Privadas,Universidades Privadas,Universidades Privadas,Universidades Privadas
CLASIFICACIÓN INSTITUCIÓN NIVEL 3,Universidades Privadas,Universidades Privadas,Universidades Privadas,Universidades Privadas,Universidades Privadas
CÓDIGO INSTITUCIÓN,1,1,1,1,1
NOMBRE INSTITUCIÓN,UNIVERSIDAD GABRIELA MISTRAL,UNIVERSIDAD GABRIELA MISTRAL,UNIVERSIDAD GABRIELA MISTRAL,UNIVERSIDAD GABRIELA MISTRAL,UNIVERSIDAD GABRIELA MISTRAL
COMUNA,PROVIDENCIA,PROVIDENCIA,PROVIDENCIA,PROVIDENCIA,PROVIDENCIA
PROVINCIA,SANTIAGO,SANTIAGO,SANTIAGO,SANTIAGO,SANTIAGO
REGIÓN,Metropolitana,Metropolitana,Metropolitana,Metropolitana,Metropolitana
NOMBRE SEDE,CASA CENTRAL,CASA CENTRAL,CASA CENTRAL,CASA CENTRAL,CASA CENTRAL
NOMBRE CARRERA,LICENCIATURA EN HISTORIA,PSICOLOGIA,PSICOLOGIA,ENFERMERIA,ANIMACION Y DISEÑO DIGITAL
ÁREA DEL CONOCIMIENTO,Ciencias Sociales,Ciencias Sociales,Ciencias Sociales,Salud,Arte y Arquitectura
CINE-F_97 ÁREA,Humanidades y Artes,"Ciencias Sociales, Enseñanza Comercial y Derecho","Ciencias Sociales, Enseñanza Comercial y Derecho",Salud y Servicios Sociales,Humanidades y Artes
CINE-F_97 SUBAREA,Humanidades,Ciencias Sociales y del Comportamiento,Ciencias Sociales y del Comportamiento,Medicina,Artes
ÁREA CARRERA GENÉRICA,Historia,Psicología,Psicología,Enfermería,Animación Digital
CINE-F_13 ÁREA,Artes y Humanidades,"Ciencias Sociales, Periodismo e Información","Ciencias Sociales, Periodismo e Información",Salud y Bienestar,Artes y Humanidades
CINE-F_13 SUBAREA,Humanidades,Ciencias Sociales y del Comportamiento,Ciencias Sociales y del Comportamiento,Salud,Artes
NIVEL GLOBAL,Pregrado,Pregrado,Pregrado,Pregrado,Pregrado
CARRERA CLASIFICACIÓN NIVEL 1,Licenciatura No Conducente a Título,Profesional Con Licenciatura,Profesional Con Licenciatura,Profesional Con Licenciatura,Profesional Con Licenciatura
CARRERA CLASIFICACIÓN NIVEL 2,Carreras Profesionales,Carreras Profesionales,Carreras Profesionales,Carreras Profesionales,Carreras Profesionales
MODALIDAD,No Presencial,Presencial,Presencial,Presencial,Presencial
JORNADA,A Distancia,Diurna,Vespertina,Diurna,Diurna
TIPO DE PLAN DE LA CARRERA,Plan Regular,Plan Regular,Plan Regular de Continuidad,Plan Regular,Plan Regular
DURACIÓN ESTUDIO CARRERA,8.0,10.0,8.0,10.0,9.0
DURACIÓN TOTAL DE LA CARRERA,8.0,10.0,8.0,10.0,9.0
CÓDIGO PROGRAMA,I1S1C10J4V1,I1S1C12J1V1,I1S1C12J2V4,I1S1C172J1V1,I1S1C194J1V1
TOTAL RANGO EDAD,10,13,15,19,9
RANGO DE EDAD 15 A 19 AÑOS,NaN,NaN,NaN,NaN,NaN
RANGO DE EDAD 20 A 24 AÑOS,1.0,1.0,NaN,1.0,7.0
RANGO DE EDAD 25 A 29 AÑOS,NaN,7.0,NaN,9.0,2.0
RANGO DE EDAD 30 A 34 AÑOS,1.0,3.0,2.0,7.0,NaN
RANGO DE EDAD 35 A 39 AÑOS,4.0,2.0,1.0,1.0,NaN
RANGO DE EDAD 40 Y MÁS AÑOS,4.0,NaN,12.0,1.0,NaN
RANGO DE EDAD SIN INFORMACIÓN,NaN,NaN,NaN,NaN,NaN
PROMEDIO EDAD PROGRAMA,"38,7",29,"45,2","30,15789474","23,55555556"
PROMEDIO EDAD MUJER,"38,5","28,9","45,69230769","30,13333333","23,2"
PROMEDIO EDAD HOMBRE,"38,83333333","29,33333333",42,"30,25",24
PROMEDIO EDAD NB,NaN,NaN,NaN,NaN,NaN

# **MATRICULAS UNIVERSIDAD**

* https://www.mifuturo.cl/bases-de-datos-de-matriculados/

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/Matricula_2007_2025_WEB_15_07_2025.csv',
                  sep = ';', encoding = 'latin-1',
                  low_memory = False, on_bad_lines = 'skip')

In [ ]:
df2.shape

(264258, 59)

In [ ]:
df2.shape

(264258, 59)

In [ ]:
df2.head().T

,0,1,2,3,4
AÑO,MAT_2025,MAT_2025,MAT_2025,MAT_2025,MAT_2025
TOTAL MATRÍCULA,245,86,15,18,114
TOTAL MATRÍCULA MUJERES,179.0,18.0,3.0,14.0,19.0
TOTAL MATRÍCULA HOMBRES,66.0,68.0,12.0,4.0,95.0
TOTAL MATRÍCULA NO BINARIOS O INDEFINIDOS,NaN,NaN,NaN,NaN,NaN
TOTAL MATRÍCULA PRIMER AÑO,94.0,29.0,NaN,6.0,28.0
TOTAL MATRÍCULA MUJERES PRIMER AÑO,67.0,3.0,NaN,5.0,4.0
TOTAL MATRÍCULA HOMBRES PRIMER AÑO,27.0,26.0,NaN,1.0,24.0
TOTAL MATRÍCULA NO BINARIOS O INDEFINIDOS PRIMER AÑO,NaN,NaN,NaN,NaN,NaN
CLASIFICACIÓN INSTITUCIÓN NIVEL 1,Institutos Profesionales,Institutos Profesionales,Institutos Profesionales,Universidades,Institutos Profesionales
CLASIFICACIÓN INSTITUCIÓN NIVEL 2,Institutos Profesionales,Institutos Profesionales,Institutos Profesionales,Universidades CRUCH,Institutos Profesionales
CLASIFICACIÓN INSTITUCIÓN NIVEL 3,Institutos Profesionales,Institutos Profesionales,Institutos Profesionales,Universidades Estatales CRUCH,Institutos Profesionales
CÓDIGO DE INSTITUCIÓN,111,111,111,83,100
NOMBRE INSTITUCIÓN,IP DUOC UC,IP DUOC UC,IP DUOC UC,UNIVERSIDAD DE PLAYA ANCHA DE CIENCIAS DE LA E...,IP INACAP
ACREDITACIÓN INSTITUCIONAL,ACREDITADA,ACREDITADA,ACREDITADA,ACREDITADA,ACREDITADA
REGIÓN,Metropolitana,Metropolitana,Metropolitana,Valparaíso,Los Lagos
PROVINCIA,SANTIAGO,CORDILLERA,SANTIAGO,VALPARAISO,OSORNO
COMUNA,MAIPU,PUENTE ALTO,CERRILLOS,VALPARAISO,OSORNO
NOMBRE SEDE,SEDE MAIPU,SEDE PUENTE ALTO,SEDE PLAZA OESTE,CASA CENTRAL (VALPARAISO),SEDE OSORNO
NOMBRE CARRERA,TECNICO EN QUIMICA Y FARMACIA,ANALISTA PROGRAMADOR COMPUTACIONAL,ANALISTA PROGRAMADOR COMPUTACIONAL,DOCTORADO INTERDISCIPLINARIO EN CIENCIAS AMBIE...,CONSTRUCCION CIVIL
ÁREA DEL CONOCIMIENTO,Salud,Tecnología,Tecnología,Ciencias Básicas,Tecnología
CINE-F 1997 ÁREA,Salud y Servicios Sociales,Ciencias,Ciencias,Ciencias,"Ingeniería, Industria y Construcción"
CINE-F 1997 SUBAREA,Medicina,Informática,Informática,Ciencias de la Vida,Arquitectura y Construcción
ÁREA CARRERA GENÉRICA,Técnico en Farmacia,Técnico en Computación e Informática,Técnico en Computación e Informática,Doctorado en Ciencias Básicas,Construcción Civil
CINE-F 2013 ÁREA,Salud y Bienestar,Tecnología de la Información y la Comunicación...,Tecnología de la Información y la Comunicación...,"Ciencias naturales, matemáticas y estadística","Ingeniería, Industria y Construcción"
CINE-F 2013 SUBAREA,Salud,Tecnología de la Información y la Comunicación...,Tecnología de la Información y la Comunicación...,Medio Ambiente,Arquitectura y Construcción
NIVEL GLOBAL,Pregrado,Pregrado,Pregrado,Posgrado,Pregrado
CARRERA CLASIFICACIÓN NIVEL 1,Técnico de Nivel Superior,Técnico de Nivel Superior,Técnico de Nivel Superior,Doctorado,Profesional Sin Licenciatura
CARRERA CLASIFICACIÓN NIVEL 2,Carreras Técnicas,Carreras Técnicas,Carreras Técnicas,Doctorado,Carreras Profesionales
MODALIDAD,Presencial,Presencial,Presencial,Presencial,Presencial
JORNADA,Diurna,Vespertina,Vespertina,Diurna,Vespertina
TIPO DE PLAN DE LA CARRERA,Plan Regular,Plan Regular,Plan Regular,Plan Regular,Plan Regular
DURACIÓN ESTUDIO CARRERA,5.0,5.0,5.0,8.0,8.0
DURACIÓN TOTAL DE CARRERA,5.0,5.0,5.0,8.0,8.0
CÓDIGO CARRERA,I111S15C407J1V1,I111S12C23J2V2,I111S10C23J2V1,I83S1C346J1V1,I100S26C176J2V1
ACREDITACIÓN CARRERA,NO ACREDITADA,NO ACREDITADA,NO ACREDITADA,ACREDITADA,NO ACREDITADA
TOTAL RANGO DE EDAD,245,86,15,18,114
RANGO DE EDAD 15 A 19 AÑOS,52.0,5.0,NaN,NaN,12.0
RANGO DE EDAD 20 A 24 AÑOS,129.0,18.0,3.0,NaN,44.0
RANGO DE EDAD 25 A 29 AÑOS,31.0,32.0,5.0,6.0,20.0
RANGO DE EDAD 30 A 34 AÑOS,14.0,17.0,5.0,5.0,15.0
RANGO DE EDAD 35 A 39 AÑOS,4.0,8.0,1.0,4.0,10.0
RANGO DE EDAD 40 Y MÁS AÑOS,15.0,6.0,1.0,3.0,13.0
RANGO DE EDAD SIN INFORMACIÓN,NaN,NaN,NaN,NaN,NaN
PROMEDIO EDAD CARRERA,"23,9","28,8","28,8","34,2",28
PROMEDIO EDAD MUJER,"24,5","30,3",27,"33,4",28
PROMEDIO EDAD HOMBRE,"22,2","28,4","29,3","36,8",28
PROMEDIO EDAD NO BINARIO,NaN,NaN,NaN,NaN,NaN
TES MUNICIPAL,46.0,14.0,4.0,3.0,49.0
TES PARTICULAR SUBVENCIONADO,162.0,58.0,7.0,10.0,51.0
TES PARTICULAR PAGADO,2.0,2.0,NaN,2.0,1.0
TES CORP. DE ADMINISTRACIÓN DELEGADA,11.0,NaN,1.0,NaN,1.0
TES SERVICIO LOCAL EDUCACION,7.0,NaN,NaN,NaN,1.0
TOTAL TES,228,74,12,15,103
% COBERTURA TES,"93,10%","86,00%","80,00%","83,30%","90,40%"
TIPO ESTABLECIMIENTO HC,142.0,44.0,8.0,14.0,49.0
TIPO ESTABLECIMIENTO TP,86.0,30.0,4.0,1.0,54.0
CLAS_EST ADULTO,43.0,12.0,5.0,NaN,23.0
CLAS_EST JOVEN,185.0,62.0,7.0,15.0,80.0

In [ ]:
df2.columns

Index(['AÑO', 'TOTAL MATRÍCULA', 'TOTAL MATRÍCULA MUJERES',
       'TOTAL MATRÍCULA HOMBRES', 'TOTAL MATRÍCULA NO BINARIOS O INDEFINIDOS',
       'TOTAL MATRÍCULA PRIMER AÑO', 'TOTAL MATRÍCULA MUJERES PRIMER AÑO',
       'TOTAL MATRÍCULA HOMBRES PRIMER AÑO',
       'TOTAL MATRÍCULA NO BINARIOS O INDEFINIDOS PRIMER AÑO',
       'CLASIFICACIÓN INSTITUCIÓN NIVEL 1',
       'CLASIFICACIÓN INSTITUCIÓN NIVEL 2',
       'CLASIFICACIÓN INSTITUCIÓN NIVEL 3', 'CÓDIGO DE INSTITUCIÓN',
       'NOMBRE INSTITUCIÓN', 'ACREDITACIÓN INSTITUCIONAL', 'REGIÓN',
       'PROVINCIA', 'COMUNA', 'NOMBRE SEDE', 'NOMBRE CARRERA',
       'ÁREA DEL CONOCIMIENTO', 'CINE-F 1997 ÁREA', 'CINE-F 1997 SUBAREA',
       'ÁREA CARRERA GENÉRICA', 'CINE-F 2013 ÁREA', 'CINE-F 2013 SUBAREA',
       'NIVEL GLOBAL', 'CARRERA CLASIFICACIÓN NIVEL 1',
       'CARRERA CLASIFICACIÓN NIVEL 2', 'MODALIDAD', 'JORNADA',
       'TIPO DE PLAN DE LA CARRERA', 'DURACIÓN ESTUDIO CARRERA',
       'DURACIÓN TOTAL DE CARRERA', 'CÓDIGO CARRERA', 'ACREDITACIÓN CARRERA',
       'TOTAL RANGO DE EDAD', 'RANGO DE EDAD 15 A 19 AÑOS',
       'RANGO DE EDAD 20 A 24 AÑOS', 'RANGO DE EDAD 25 A 29 AÑOS',
       'RANGO DE EDAD 30 A 34 AÑOS', 'RANGO DE EDAD 35 A 39 AÑOS',
       'RANGO DE EDAD 40 Y MÁS AÑOS', 'RANGO DE EDAD SIN INFORMACIÓN',
       'PROMEDIO EDAD CARRERA     ', 'PROMEDIO EDAD MUJER     ',
       'PROMEDIO EDAD HOMBRE     ', ' PROMEDIO EDAD NO BINARIO ',
       'TES MUNICIPAL', 'TES PARTICULAR SUBVENCIONADO',
       'TES PARTICULAR PAGADO', 'TES CORP. DE ADMINISTRACIÓN DELEGADA',
       'TES SERVICIO LOCAL EDUCACION', 'TOTAL TES', '% COBERTURA TES',
       'TIPO ESTABLECIMIENTO HC', 'TIPO ESTABLECIMIENTO TP', 'CLAS_EST ADULTO',
       'CLAS_EST JOVEN'],
      dtype='object')

# **LICENCIAS**

El resto de la data la puedan buscar acá:
* https://www.superdesalud.gob.cl/tax-biblioteca-digital/datos-abiertos-de-isapres-6988/

In [ ]:
df3 = pd.read_csv('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/dataset_Licencias_Medicas_2025t1.txt',
                  sep = '|', encoding = 'latin-1',
                  low_memory = False, on_bad_lines = 'skip')

In [ ]:
df3.shape

(292155, 45)

In [ ]:
df3.head()

,67,2025t1,1311,2025t1.1,84,2025t1.2,31-35,Femenino,Servicios,Otro Profesional,...,3309063,Su Domicilio,Z. Sin Clasificar,42,2011t1,2011t1.1,565169,1311.1,2025,Unnamed: 44
0,67,2025t1,1897,2025t1,11,2025t1,56-60,Masculino,Construccion,Tecnico,...,1529982,Su Domicilio,Z. Sin Clasificar,0,1987t1,1999t1,2441375,1897,1800,NaN
1,99,2025t1,408874,2025t1,15,2025t1,31-35,Femenino,Otros,Otro Profesional,...,1529982,Su Domicilio,Z. Sin Clasificar,0,2017t2,2018t1,1616598,3002,1800,NaN
2,67,2025t1,3439,2024t4,30,2024t4,26-30,Femenino,Finanzas,Otros,...,1529982,Su Domicilio,Reposo Injustificado,0,2012t4,2012t4,1248401,3439,1800,NaN
3,78,2025t1,1825635,2025t1,84,2025t1,31-35,Femenino,Servicios,Otros,...,2025157968,Su Domicilio,Z. Sin Clasificar,42,2012t1,2020t3,2040683,4987,2025,NaN
4,99,2025t1,1804114,2025t1,84,2025t1,31-35,Femenino,Servicios,Otros,...,2025019132,Su Domicilio,Z. Sin Clasificar,114,2020t2,2024t3,2119750,4987,2024,NaN

In [ ]:
df3.columns

Index(['67', '2025t1', '1311', '2025t1.1', '84', '2025t1.2', '31-35',
       'Femenino', 'Servicios', 'Otro Profesional', 'Licencia Maternal',
       'Reposo Total', '776791', 'Medico', 'Licencia Maternal.1', '84.1',
       'Z00-Z99', 'Autoricese', 'Continuacion', 'Reposo Total.1',
       'Verificado Requisitos Legales', '2025t1.3', '2025t1.4', '2025t1.5',
       '13', 'Trab. Independiente', 'Isapre', '79', '1488280', '181603',
       '2025t1.6', 'SI', '2024', '232975', 'Z00-Z99.1', '3309063',
       'Su Domicilio', 'Z. Sin Clasificar', '42', '2011t1', '2011t1.1',
       '565169', '1311.1', '2025', 'Unnamed: 44'],
      dtype='object')

In [ ]:
len(df3.columns)

45

In [ ]:
df3.columns =  [ "CodigoIsapre",  "FechaInformacion", "RunTrabajador","FechaEmisionLicencia", "NumeroDias", "FechaInicioReposo",  "EdadTrabajador",
    "SexoTrabajador","ActividadLaboral","Ocupacion","TipoLicencia",
    "CaracteristicasReposo","RunProfesional", "TipoProfesional",  "TipoLicenciaContraloria","NumeroDiasAutorizados",
    "DiagnosticoPrincipal", "TipoResolucion","Periodo","ReposoAutorizado",
    "DerechoSubsidio", "FechaRecepcionIsapre","FechaResolucionIsapre","FechaRecepcionEmpleador",
    "Region","CalidadTrabajador","EntidadPagadora","NumeroDiasPagar", "MontoSubsidioLiquido", "MontoAportePrevisionalIsapre",
    "FechaInicioPago", "Recuperabilidad", "FechaConcepcion",  "MontoAportePrevisionalPensiones", "OtrosDiagnosticos", "RunHijo",
    "LugarReposo","CausaRechazoModificacion","NumeroDiasPreviosAutorizados",  "FechaPrimeraAfiliacionPrevisional","FechaContratoTrabajo",
    "MontoBaseCalculoSubsidio", "RutEmpleador", "FechaNacimientoHijo", 'eliminar']

In [ ]:
df3.drop(columns = ['eliminar'], inplace = True)

In [ ]:
df3.head().T

,0,1,2,3,4
CodigoIsapre,67,99,67,78,99
FechaInformacion,2025t1,2025t1,2025t1,2025t1,2025t1
RunTrabajador,1897,408874,3439,1825635,1804114
FechaEmisionLicencia,2025t1,2025t1,2024t4,2025t1,2025t1
NumeroDias,11,15,30,84,84
FechaInicioReposo,2025t1,2025t1,2024t4,2025t1,2025t1
EdadTrabajador,56-60,31-35,26-30,31-35,31-35
SexoTrabajador,Masculino,Femenino,Femenino,Femenino,Femenino
ActividadLaboral,Construccion,Otros,Finanzas,Servicios,Servicios
Ocupacion,Tecnico,Otro Profesional,Otros,Otros,Otros
TipoLicencia,Enf. o Acc. no del Trabajo,Enf. o Acc. no del Trabajo,Enf. o Acc. no del Trabajo,Licencia Maternal,Licencia Maternal
CaracteristicasReposo,Reposo Total,Reposo Total,Reposo Total,Reposo Total,Reposo Total
RunProfesional,43503774,1933963,3385356,262470496,6295554
TipoProfesional,Medico,Medico,Medico,Medico,Matrona
TipoLicenciaContraloria,Enf. o Acc. no del Trabajo,Enf. o Acc. no del Trabajo,Enf. o Acc. no del Trabajo,Licencia Maternal,Licencia Maternal
NumeroDiasAutorizados,11,15,14,81,84
DiagnosticoPrincipal,C00-D48,F00-F99,F00-F99,Z00-Z99,None
TipoResolucion,Autoricese,Autoricese,Reducese,Autoricese,Autoricese
Periodo,Primera,Primera,Primera,Continuacion,Continuacion
ReposoAutorizado,Reposo Total,Reposo Total,Reposo Total,Reposo Total,Reposo Total
DerechoSubsidio,Verificado Requisitos Legales,Verificado Requisitos Legales,Verificado Requisitos Legales,Verificado Requisitos Legales,Verificado Requisitos Legales
FechaRecepcionIsapre,2025t1,2025t1,2024t4,2025t1,2025t1
FechaResolucionIsapre,2025t1,2025t1,2024t4,2025t1,2025t1
FechaRecepcionEmpleador,2025t1,2025t1,2024t4,2025t1,2025t1
Region,6,13,8,12,12
CalidadTrabajador,Trab. Independiente,Trab. Dep. Sector Privado,Trab. Independiente,Trab. Pub. No Afecto 18.834,Trab. Pub. Afecto 18.834
EntidadPagadora,Isapre,Isapre,Isapre,Isapre,Isapre
NumeroDiasPagar,11,15,14,81,84
MontoSubsidioLiquido,895171,802263,582587,5509844,5935300
MontoAportePrevisionalIsapre,94065,70425,50397,707301,696807
FechaInicioPago,2025t2,2025t2,2025t1,2025t1,2025t2
Recuperabilidad,SI,SI,SI,SI,SI
FechaConcepcion,1800,1800,1800,2024,1800
MontoAportePrevisionalPensiones,150214,112276,86970,1000307,940194
OtrosDiagnosticos,C00-D48,None,F00-F99,None,None
RunHijo,1529982,1529982,1529982,2025157968,2025019132
LugarReposo,Su Domicilio,Su Domicilio,Su Domicilio,Su Domicilio,Su Domicilio
CausaRechazoModificacion,Z. Sin Clasificar,Z. Sin Clasificar,Reposo Injustificado,Z. Sin Clasificar,Z. Sin Clasificar
NumeroDiasPreviosAutorizados,0,0,0,42,114
FechaPrimeraAfiliacionPrevisional,1987t1,2017t2,2012t4,2012t1,2020t2
FechaContratoTrabajo,1999t1,2018t1,2012t4,2020t3,2024t3
MontoBaseCalculoSubsidio,2441375,1616598,1248401,2040683,2119750
RutEmpleador,1897,3002,3439,4987,4987
FechaNacimientoHijo,1800,1800,1800,2025,2024

# **GASTOS CAMPAÑA PARLAMENTARIAS**

* Manual: https://drive.google.com/file/d/1tjPzWS00shdjz2Xl8QCFL_pv5QLzzB6x/view?usp=sharing

In [ ]:
import pandas as pd

In [ ]:
excel_file = pd.ExcelFile('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/reporte_ingresos_gastos_definitivas_2025.xlsx')
sheet_names = excel_file.sheet_names
print(sheet_names) # NOMBRE DE HOJAS CON INFORMACIÓN DISPONIBLES

['Resultado Auditoria Cuentas', 'FORMULARIO 87 Y 88', 'FORMULARIO AUXILIAR 101', 'FORMULARIO AUXILIAR 102', 'FORMULARIO AUXILIAR 103', 'FORMULARIO AUXILIAR 104', 'FORMULARIO AUXILIAR 105', 'FORMULARIO AUXILIAR 106', 'FORMULARIO AUXILIAR 107', 'FORMULARIO AUXILIAR 108']

In [ ]:
df4 = pd.read_excel('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/reporte_ingresos_gastos_definitivas_2025.xlsx')

In [ ]:
df4.shape

(1287, 6)

In [ ]:
df4.head()  # resultados de revisión de servel

,Eleccion,Tipo,Región,Territorio Electoral,Nombre Candidatura,Estado Cuenta
0,DIPUTADO,Candidatura,REGIÓN DE ARICA Y PARINACOTA,DISTRITO 1,MARCELO ZARA PIZARRO,Aprueba con observaciones
1,DIPUTADO,Candidatura,REGIÓN DE ARICA Y PARINACOTA,DISTRITO 1,RODRIGO CUEVAS TRONCOSO,Rechaza
2,DIPUTADO,Candidatura,REGIÓN DE ARICA Y PARINACOTA,DISTRITO 1,CAMILO MARTIN JOFRE CAÑIPA,Aprueba
3,DIPUTADO,Candidatura,REGIÓN DE ARICA Y PARINACOTA,DISTRITO 1,RICARDO SANZANA OTEIZA,Aprueba con observaciones
4,DIPUTADO,Candidatura,REGIÓN DE ARICA Y PARINACOTA,DISTRITO 1,LUIS MALLA VALENZUELA,Aprueba con observaciones

In [ ]:
df4b = pd.read_excel('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/reporte_ingresos_gastos_definitivas_2025.xlsx',
                     sheet_name = 'FORMULARIO 87 Y 88', skiprows= 10)
## resumen ingresos/egresos

In [ ]:
df4b.shape

(97344, 21)

In [ ]:
df4b.head().T

,0,1,2,3,4
TIPO CUENTA,Candidato,Candidato,Candidato,Candidato,Candidato
TIPO,INGRESOS,INGRESOS,INGRESOS,INGRESOS,INGRESOS
ELECCIÓN,DIPUTADO,DIPUTADO,DIPUTADO,DIPUTADO,DIPUTADO
REGIÓN,REGIÓN DE TARAPACÁ,REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS,REGIÓN METROPOLITANA DE SANTIAGO,REGIÓN DEL BIOBÍO,REGIÓN DE COQUIMBO
TERRITORIO ELECTORAL,DISTRITO 2,DISTRITO 16,DISTRITO 14,DISTRITO 21,DISTRITO 5
NOMBRE DE CANDIDATURA/PARTIDO,JORGE MUÑOZ OYARCE,RICARDO NEUMANN BERTIN,ROBERTO SOTO FERRADA,CARLOS FELIPE AGURTO PEDREROS,BERNARDO SALINAS MAYA
NOMBRE PARTIDO,PARTIDO REPUBLICANO DE CHILE,UNION DEMOCRATA INDEPENDIENTE,PARTIDO SOCIALISTA DE CHILE,PARTIDO DE LA GENTE,INDEPENDIENTES
PACTO,CAMBIO POR CHILE,CHILE GRANDE Y UNIDO,UNIDAD POR CHILE,PARTIDO DE LA GENTE,UNIDAD POR CHILE
SUBPACTO,NaN,NaN,NaN,NaN,NaN
RUT APORTANTE O PROVEEDOR,NaN,97080000.0,NaN,97030000.0,NaN
DV APORTANTE/PROVEEDOR,,K,,7,
NOMBRE APORTANTE/PROVEEDOR,Formulario 107,BANCO BICE,Formulario 103,banco estado,FRANCISCA NARVAEZ MOLINA
FECHA DOCUMENTO,15-11-2025,29-10-2025,28-11-2025,15-10-2025,15-11-2025
MONTO,$ 0,$ 24.196.520,$ 200.000,$ 3.172.962,$ 350.000
TIPO DOCUMENTO,ND,MA,ND,MA,ND
DESCRIPCIÓN T/D,No definido,Mandato,No definido,Mandato,No definido
NÚMERO DOCUMENTO,586867,21037,594205,15707,1
TIPO CUENTA.1,143,141,1112,141,121
DESCRIPCIÓN T/C,Reembolso por Documentos pendientes de pago,Reembolso por Créditos con mandato,Aporte propio en especies o servicios de la ca...,Reembolso por Créditos con mandato,Aportes en especies o servicios de terceros
GLOSA DOCUMENTO,Detalle de reembolso solicitado,CREDITO CON MANDATO,Registro de Vehículos,mandato,ADMINISTRADOR ELECTORAL
TIPO REEMBOLSO,None,None,None,None,None

In [ ]:
df4c = pd.read_excel('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/reporte_ingresos_gastos_definitivas_2025.xlsx',
                     sheet_name = 'FORMULARIO AUXILIAR 107', skiprows= 10)
# resumen de reembolsos solicitados

In [ ]:
df4c.shape

(7294, 15)

In [ ]:
df4c.head().T

,0,1,2,3,4
TIPO CUENTA,Candidato,Candidato,Candidato,Candidato,Candidato
NOMBRE DE CANDIDATURA,DORIS,CAROLINA,CAROLINA,CAROLINA,CAROLINA
APELLIDO PATERNO DE CANDIDATURA,BLANCO,TELLO,TELLO,TELLO,TELLO
APELLIDO MATERNO DE CANDIDATURA,LLANQUILEO,ROJAS,ROJAS,ROJAS,ROJAS
NOMBRE PARTIDO,None,None,None,None,None
ELECCIÓN,DIPUTADO,DIPUTADO,DIPUTADO,DIPUTADO,DIPUTADO
RUT PROVEEDOR,78115381.0,NaN,NaN,NaN,76080231.0
DV PROVEEDOR,8,,,,k
RAZON SOCIAL,AGENCIA DE NOTICIAS RODRIGO GO,Veroonica Vilches,Camila Romero,Javier Vadillo,Soc periodística El Ciudadano
NUMERO DOCUMENTO,2,522,107,138,965
FECHA DOCUMENTO,12-11-2025,12-11-2025,12-11-2025,30-08-2025,05-11-2025
GLOSA,PUBLICIDAD RRSS 30 DÍAS DESDE El 14 OCTUBRE AL...,Encargada de Voluntarios,Jefa de campaña,Administrador Electoral,Pack Posicionamiento
MONTO,$ 184.450,$ 1.000.000,$ 4.000.000,$ 4.000.000,$ 2.000.000
DETALLE REEMBOLSO,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato
NOMBRE FORMULARIO,Formulario 107,Formulario 107,Formulario 107,Formulario 107,Formulario 107

# **GASTOS CAMPAÑA MUNICIPALES**
Manual: https://drive.google.com/file/d/1vE2n0G8J963CUlq_24DkbvNr2rI8hXUe/view?usp=sharing

In [ ]:
import pandas as pd

In [ ]:
excel_file = pd.ExcelFile('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/Reporte_Ingresos_Gastos_Definitivas2024.xlsx')
sheet_names = excel_file.sheet_names
print(sheet_names)  # NOMBRE DE HOJAS CON INFORMACIÓN DISPONIBLES

['Resultado Auditoria Cuentas', 'INGRESOS Y GASTOS', 'FORMULARIO AUXILIAR 101', 'FORMULARIO AUXILIAR 102', 'FORMULARIO AUXILIAR 103', 'FORMULARIO AUXILIAR 104', 'FORMULARIO AUXILIAR 105', 'FORMULARIO AUXILIAR 106', 'FORMULARIO AUXILIAR 107', 'FORMULARIO AUXILIAR 108']

In [ ]:
df5 = pd.read_excel('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/Reporte_Ingresos_Gastos_Definitivas2024.xlsx')

In [ ]:
df5.shape

(18122, 6)

In [ ]:
df5.head()  # resultados de revisión de servel

,Eleccion,Tipo,Región,Territorio Electoral,Nombre Candidatura,Estado Cuenta
0,ALCALDE,Candidatura,REGIÓN DE ÑUBLE,BULNES,JUAN AREVALO ROJAS,Aprueba con Observaciones
1,ALCALDE,Candidatura,REGIÓN DE ÑUBLE,BULNES,GONZALO BUSTAMANTE TRONCOSO,Aprueba
2,ALCALDE,Candidatura,REGIÓN DE ÑUBLE,BULNES,PATRICIO ANDRES VELOZO FLORES,Aprueba con Observaciones
3,ALCALDE,Candidatura,REGIÓN DE ÑUBLE,BULNES,GUILLERMO ALEJANDRO YEBER RODRIGUEZ,Aprueba
4,ALCALDE,Candidatura,REGIÓN DE ÑUBLE,CHILLÁN,FERNANDO BRIONES CONTRERAS,Rechaza

In [ ]:
df5b = pd.read_excel('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/Reporte_Ingresos_Gastos_Definitivas2024.xlsx',
                     sheet_name = 'INGRESOS Y GASTOS', skiprows= 10)
## resumen ingresos/gastos

In [ ]:
df5b.shape

(352676, 21)

In [ ]:
df5b.head().T

,0,1,2,3,4
TIPO CUENTA,Candidato,Candidato,Candidato,Candidato,Candidato
TIPO,INGRESOS,INGRESOS,INGRESOS,INGRESOS,INGRESOS
ELECCIÓN,CONCEJAL,CONCEJAL,CONCEJAL,CONCEJAL,CONCEJAL
REGIÓN,REGIÓN DE ARICA Y PARINACOTA,REGIÓN DE LOS RÍOS,REGIÓN DE VALPARAÍSO,REGIÓN DE VALPARAÍSO,REGIÓN DE LA ARAUCANÍA
TERRITORIO ELECTORAL,PUTRE,VALDIVIA,LIMACHE,LIMACHE,ERCILLA
NOMBRE DE CANDIDATURA/PARTIDO,ODLANIER VELIZ MENA,ALBERTO ERICO VASQUEZ CARDENAS,MATIAS IGNACIO MADRIAZA MADARIAGA,MATIAS IGNACIO MADRIAZA MADARIAGA,CECILIA ANDREA VARELA ZAMBRANO
NOMBRE PARTIDO,INDEPENDIENTES,INDEPENDIENTES,INDEPENDIENTES,INDEPENDIENTES,INDEPENDIENTES
PACTO,CHILE VAMOS UDI-EVOPOLI E INDEPENDIENTES,CHILE VAMOS RENOVACIÓN NACIONAL - INDEPENDIENTES,IZQUIERDA ECOLOGISTA POPULAR,IZQUIERDA ECOLOGISTA POPULAR,TU COMUNA RADICAL
SUBPACTO,UDI - INDEPENDIENTES,NaN,POPULARES E INDEPENDIENTES,POPULARES E INDEPENDIENTES,NaN
RUT APORTANTE O PROVEEDOR,71552600.0,71395000.0,NaN,NaN,72551500.0
DV APORTANTE/PROVEEDOR,k,9,NaN,NaN,6
NOMBRE APORTANTE/PROVEEDOR,Unión Demócrata Independiente,RENOVACION NACIONAL,MATIAS IGNACIO MADRIAZA MADARIAGA,NaN,PARTIDO RADICAL DE CHILE
FECHA DOCUMENTO,12-02-2025,19-02-2025,16-03-2025,16-03-2025,01-10-2024
MONTO,150000,200000,149500,50000,50000
TIPO DOCUMENTO,ND,ND,ND,ND,ND
DESCRIPCIÓN T/D,No definido,No definido,No definido,No definido,No definido
NÚMERO DOCUMENTO,6786.0,1.0,1.0,1.0,1.0
TIPO CUENTA.1,116.0,116.0,1111.0,114.0,116.0
DESCRIPCIÓN T/C,Aporte en dinero desde el partido político a c...,Aporte en dinero desde el partido político a c...,Aporte propio en efectivo,Aportes menores sin publicidad,Aporte en dinero desde el partido político a c...
GLOSA DOCUMENTO,aporte partido,"Se incorpora registro, según SRA","Se incorpora registro, según SRA","Se incorpora registro, según SRA\t",aporte en efectivo del partido político por SRA
TIPO REEMBOLSO,NaN,NaN,NaN,NaN,NaN

In [ ]:
df5c = pd.read_excel('/content/drive/MyDrive/ANALISIS_DATOS_PYTHON/2026/PROYECTO/DOCUMENTOS/dataset/Reporte_Ingresos_Gastos_Definitivas2024.xlsx',
                     sheet_name = 'FORMULARIO AUXILIAR 107', skiprows= 10)
# resumen de reembolsos solicitados

In [ ]:
df5c.shape

(28278, 14)

In [ ]:
df5c.head().T

,0,1,2,3,4
NOMBRE DE CANDIDATURA,ALICIA,HECTOR,JAIME,DANIEL,SERGIO
APELLIDO PATERNO DE CANDIDATURA,BAHAMONDES,MEDINA,GONZALEZ,DOMINGUEZ,GIACAMAN
APELLIDO MATERNO DE CANDIDATURA,ARANEDA,ALEGRIA,KAZAZIAN,GONZALEZ,GARCIA
NOMBRE PARTIDO,NaN,NaN,NaN,NaN,NaN
ELECCIÓN,CONCEJAL,CONCEJAL,CONSEJERO REGIONAL,ALCALDE,GOBERNADOR REGIONAL
RUT PROVEEDOR,NaN,76035726.0,77559829.0,79584090.0,97030000.0
DV PROVEEDOR,NaN,K,8,7,7
RAZON SOCIAL,Rene Miguel Millar Barria,RADIODIFUSORA JUAN MATIAS FUET,IDEAS COLCHAGUA SPA,SOCIEDAD COMERCIAL RADIO EMISO,banco estado
NUMERO DOCUMENTO,936,1267,54,6912,37963083
FECHA DOCUMENTO,22-10-2024,23-10-2024,24-10-2024,24-10-2024,09-10-2024
GLOSA,Impresiones palomas,RADIIODIFUSORA,CONSULTORIA CAMPAÑA,Difusión publicidad Electoral Emitida en Radio...,re embolso fiscal eleccion gobernador
MONTO,168900,142800,500000,1279770,105080689
DETALLE REEMBOLSO,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato,Reembolso hacia el mismo candidato
NOMBRE FORMULARIO,Fomulario 107,Fomulario 107,Fomulario 107,Fomulario 107,Fomulario 107